
// Generated by Cadence Encounter(R) RTL Compiler RC11.10 - v11.10-p005_1

// Verification Directory fv/vga_vtim 

module top(clk, ena, rst, Tsync, Tgdel, Tgate, Tlen, Sync, Gate,
     Done, prev_state, prev_cnt, prev_cnt_len);
  input clk, ena, rst;
  input [7:0] Tsync, Tgdel;
  input [15:0] Tgate, Tlen, prev_cnt, prev_cnt_len;
  input [4:0] prev_state;
  output Sync, Gate, Done;
  wire clk, ena, rst;
  wire [7:0] Tsync, Tgdel;
  wire [15:0] Tgate, Tlen, prev_cnt, prev_cnt_len;
  wire [4:0] prev_state;
  wire Sync, Gate, Done;
  wire n_97, n_100, n_269, n_343, n_344, n_345, n_346, n_347;
  wire n_348, n_349, n_350, n_351, n_352, n_353, n_354, n_355;
  wire n_356, n_357, n_358, n_359, n_360, n_361, n_362, n_363;
  wire n_364, n_365, n_366, n_367, n_368, n_369;
  assign Gate = 1'b0;
  nor g33 (n_269, Done, n_369);
  not g40 (Sync, n_269);
  nor g59 (n_100, n_359, prev_cnt_len[1], prev_cnt_len[12],
       prev_state[2]);
  nor g63 (n_97, n_364, prev_cnt_len[11], prev_cnt_len[15], rst);
  not g307 (n_343, prev_state[2]);
  not g308 (n_344, prev_cnt_len[4]);
  not g309 (n_345, prev_state[3]);
  not g310 (n_346, prev_state[4]);
  not g311 (n_347, prev_cnt_len[2]);
  not g312 (n_348, prev_cnt_len[6]);
  not g313 (n_349, prev_cnt_len[8]);
  not g314 (n_350, prev_cnt_len[3]);
  not g315 (n_351, prev_cnt_len[7]);
  not g316 (n_352, prev_cnt_len[9]);
  not g317 (n_353, prev_cnt_len[0]);
  not g318 (n_354, prev_cnt_len[13]);
  not g319 (n_355, prev_state[1]);
  not g320 (n_356, ena);
  not g321 (n_357, prev_state[0]);
  not g322 (n_358, prev_cnt_len[5]);
  nand g323 (n_359, prev_state[4], n_345, n_344);
  not g324 (n_360, n_100);
  nand g325 (n_361, n_349, n_348, n_347);
  nor g326 (n_362, n_361, n_356, prev_cnt_len[14], prev_cnt_len[10]);
  not g327 (n_363, n_362);
  nand g328 (n_364, n_352, n_351, n_350);
  nand g329 (n_365, n_355, n_354, n_353);
  not g330 (n_366, n_365);
  nand g331 (n_367, n_97, n_366, n_357, n_358);
  nor g332 (Done, n_360, n_363, n_367);
  nand g333 (n_368, ena, n_346, n_345, n_343);
  nor g334 (n_369, n_368, rst, prev_state[1], n_357);
endmodule

