
// Generated by Cadence Encounter(R) RTL Compiler RC11.10 - v11.10-p005_1

// Verification Directory fv/top 

module top(prim_out, sel_prim);
  input [18:0] sel_prim;
  output [31:0] prim_out;
  wire [18:0] sel_prim;
  wire [31:0] prim_out;
  wire ctl_sel_prim_412_12_n_205, ctl_sel_prim_412_12_n_308,
       ctl_sel_prim_412_12_n_411, ctl_sel_prim_412_12_n_442,
       ctl_sel_prim_412_12_n_467, ctl_sel_prim_412_12_n_493,
       ctl_sel_prim_412_12_n_538, n_654;
  wire n_664, n_680, n_710, n_715, n_726, n_736, n_753, n_778;
  wire n_890, n_891, n_898, n_899, n_900, n_901, n_902, n_903;
  wire n_904, n_905, n_906, n_907, n_908, n_909, n_910, n_911;
  wire n_912, n_914, n_915, n_918, n_919, n_921, n_924, n_925;
  wire n_928, n_929, n_930, n_932, n_936, n_939, n_940, n_944;
  wire n_952, n_953, n_1108, n_1291, n_1314, n_1317, n_1318, n_1319;
  wire n_1320, n_1321, n_1322, n_1323, n_1324, n_1325, n_1326, n_1327;
  wire n_1328, n_1329, n_1330, n_1331, n_1332, n_1333, n_1334, n_1335;
  wire n_1336, n_1337, n_1338, n_1339, n_1340, n_1341, n_1342, n_1343;
  wire n_1344, n_1345, n_1346, n_1347, n_1348, n_1349, n_1350, n_1351;
  wire n_1352, n_1353, n_1354, n_1355, n_1356, n_1357, n_1358, n_1359;
  wire n_1360, n_1361, n_1362, n_1363, n_1364, n_1365, n_1366, n_1367;
  wire n_1368, n_1369, n_1370, n_1371, n_1372, n_1373, n_1374, n_1375;
  wire n_1376, n_1377, n_1378, n_1379, n_1380, n_1381, n_1382, n_1383;
  wire n_1384, n_1385, n_1386, n_1387, n_1388, n_1389, n_1390, n_1391;
  wire n_1392, n_1393, n_1394, n_1395, n_1396, n_1397, n_1398, n_1399;
  wire n_1400, n_1401, n_1402, n_1403, n_1404, n_1405, n_1406, n_1407;
  wire n_1408, n_1409, n_1410, n_1411, n_1412;
  assign prim_out[0] = 1'b0;
  assign prim_out[2] = prim_out[5];
  assign prim_out[3] = 1'b1;
  assign prim_out[4] = prim_out[5];
  assign prim_out[8] = prim_out[12];
  assign prim_out[9] = prim_out[11];
  assign prim_out[10] = prim_out[12];
  assign prim_out[18] = prim_out[26];
  assign prim_out[19] = prim_out[27];
  not ctl_sel_prim_412_12_g171 (prim_out[1], prim_out[5]);
  nor ctl_sel_prim_412_12_g150 (ctl_sel_prim_412_12_n_493, n_1335,
       ctl_sel_prim_412_12_n_411, ctl_sel_prim_412_12_n_308,
       ctl_sel_prim_412_12_n_205);
  nand ctl_sel_prim_412_12_g177 (ctl_sel_prim_412_12_n_538, n_1342,
       n_1349, n_918, n_919);
  nor ctl_sel_prim_412_12_g134 (ctl_sel_prim_412_12_n_442, n_1367,
       ctl_sel_prim_412_12_n_411, ctl_sel_prim_412_12_n_308,
       ctl_sel_prim_412_12_n_205);
  nor ctl_sel_prim_412_12_g142 (ctl_sel_prim_412_12_n_467, n_1368,
       ctl_sel_prim_412_12_n_411, ctl_sel_prim_412_12_n_308,
       ctl_sel_prim_412_12_n_205);
  nand g443 (n_914, n_901, n_902, n_903, n_904);
  nand g444 (n_915, prim_out[5], n_905, n_906, n_907);
  nand g450 (n_921, n_890, n_891, n_908, n_909);
  nand g453 (n_924, n_902, n_903, n_904, n_910);
  nand g454 (n_925, n_905, n_906, n_907, n_911);
  nand g455 (n_680, prim_out[5], n_898);
  nand g457 (n_928, n_890, n_899, n_908, n_909);
  nand g458 (n_929, n_900, n_901, n_902, n_903);
  nand g459 (n_930, n_904, n_906, n_907, n_910);
  nand g461 (n_932, prim_out[5], n_903, n_904, n_906);
  nand g465 (n_936, n_898, n_901, n_904, n_905);
  nand g468 (n_939, n_890, n_891, n_900, n_909);
  nand g469 (n_940, n_903, n_904, n_906, n_911);
  nand g473 (n_944, n_890, n_900, n_903, n_904);
  nand g481 (n_952, n_898, n_899, n_900, n_901);
  nand g482 (n_953, n_890, n_898, n_899, n_900);
  not g654 (prim_out[30], n_664);
  not g669 (prim_out[23], n_715);
  not g677 (n_1108, prim_out[17]);
  not g692 (prim_out[28], n_680);
  not g736 (prim_out[31], n_654);
  not g738 (prim_out[24], n_710);
  not g739 (prim_out[22], n_726);
  not g741 (prim_out[20], n_736);
  not g742 (prim_out[16], n_753);
  not g744 (prim_out[13], n_778);
  not g1024 (n_1317, sel_prim[0]);
  not g1025 (n_1318, sel_prim[1]);
  not g1026 (n_1319, sel_prim[2]);
  not g1027 (n_1320, sel_prim[3]);
  not g1028 (n_1321, sel_prim[4]);
  not g1029 (n_1322, sel_prim[5]);
  not g1030 (n_1323, sel_prim[6]);
  not g1031 (n_1324, sel_prim[7]);
  not g1032 (n_1325, sel_prim[8]);
  not g1033 (n_1326, sel_prim[9]);
  not g1034 (n_1327, sel_prim[10]);
  not g1035 (n_1328, sel_prim[15]);
  not g1036 (n_1329, sel_prim[16]);
  not g1037 (n_1330, sel_prim[17]);
  not g1038 (n_1331, sel_prim[11]);
  not g1039 (n_1332, sel_prim[12]);
  not g1040 (n_1333, sel_prim[13]);
  not g1041 (n_1334, sel_prim[14]);
  nand g1042 (n_1335, sel_prim[18], n_1330, n_1329, n_1328);
  nand g1043 (ctl_sel_prim_412_12_n_411, n_1334, n_1333, n_1332,
       n_1331);
  nand g1044 (ctl_sel_prim_412_12_n_308, n_1327, n_1326, n_1325,
       n_1324);
  not g1045 (n_1336, ctl_sel_prim_412_12_n_308);
  nand g1046 (ctl_sel_prim_412_12_n_205, n_1323, n_1322, n_1321,
       n_1320);
  not g1047 (n_1337, ctl_sel_prim_412_12_n_205);
  nand g1048 (n_1291, n_1319, n_1318, n_1317);
  not g1049 (n_1338, n_1291);
  nand g1050 (prim_out[5], ctl_sel_prim_412_12_n_493, n_1338);
  nand g1051 (n_890, sel_prim[1], n_1317);
  not g1052 (n_1339, n_890);
  nand g1053 (n_891, sel_prim[2], n_1318, n_1317);
  not g1054 (n_1340, n_891);
  nand g1055 (n_908, n_1338, sel_prim[3]);
  not g1056 (n_1341, n_908);
  nor g1057 (n_1342, n_1339, n_1340, n_1341, sel_prim[0]);
  nand g1058 (n_1343, sel_prim[6], n_1322, n_1321, n_1320);
  not g1059 (n_1344, n_1343);
  nand g1060 (n_899, n_1338, n_1344);
  not g1061 (n_1345, n_899);
  nand g1062 (n_898, n_1338, sel_prim[5], n_1321, n_1320);
  not g1063 (n_1346, n_898);
  nand g1064 (n_900, n_1338, n_1337, sel_prim[7]);
  not g1065 (n_1347, n_900);
  nand g1066 (n_909, n_1338, sel_prim[4], n_1320);
  not g1067 (n_1348, n_909);
  nor g1068 (n_1349, n_1345, n_1346, n_1347, n_1348);
  nand g1069 (n_901, n_1338, n_1337, sel_prim[8], n_1324);
  not g1070 (n_1350, n_901);
  nor g1071 (n_1351, ctl_sel_prim_412_12_n_205, n_1326, sel_prim[8],
       sel_prim[7]);
  nand g1072 (n_902, n_1338, n_1351);
  not g1073 (n_1352, n_902);
  nand g1074 (n_1353, sel_prim[10], n_1326, n_1325, n_1324);
  not g1075 (n_1354, n_1353);
  nand g1076 (n_903, n_1338, n_1337, n_1354);
  not g1077 (n_1355, n_903);
  nand g1078 (n_910, n_1338, n_1337, n_1336, sel_prim[11]);
  not g1079 (n_1356, n_910);
  nor g1080 (n_918, n_1350, n_1352, n_1355, n_1356);
  nor g1081 (n_1357, ctl_sel_prim_412_12_n_205,
       ctl_sel_prim_412_12_n_308, n_1332, sel_prim[11]);
  nand g1082 (n_904, n_1338, n_1357);
  not g1083 (n_1358, n_904);
  nand g1084 (n_1359, sel_prim[13], n_1332, n_1331);
  not g1085 (n_1360, n_1359);
  nand g1086 (n_905, n_1338, n_1337, n_1336, n_1360);
  not g1087 (n_1361, n_905);
  nand g1088 (n_1362, sel_prim[14], n_1333, n_1332, n_1331);
  not g1089 (n_1363, n_1362);
  nand g1090 (n_906, n_1338, n_1337, n_1336, n_1363);
  not g1091 (n_1364, n_906);
  nor g1092 (n_1365, ctl_sel_prim_412_12_n_205,
       ctl_sel_prim_412_12_n_308, ctl_sel_prim_412_12_n_411, n_1328);
  nand g1093 (n_907, n_1338, n_1365);
  not g1094 (n_1366, n_907);
  nor g1095 (n_919, n_1358, n_1361, n_1364, n_1366);
  nand g1096 (n_1367, sel_prim[16], n_1328);
  nand g1097 (n_1368, sel_prim[17], n_1329, n_1328);
  not g1098 (n_1369, n_914);
  not g1099 (n_1370, n_915);
  not g1100 (n_1371, n_921);
  not g1101 (n_1372, n_924);
  nand g1102 (n_911, ctl_sel_prim_412_12_n_442, n_1338);
  not g1103 (n_1373, n_911);
  not g1104 (n_1374, n_925);
  not g1105 (n_1375, n_928);
  not g1106 (n_1376, n_929);
  not g1107 (n_1377, n_930);
  not g1108 (n_1378, n_932);
  not g1109 (n_1379, n_936);
  not g1110 (n_1380, n_939);
  not g1111 (n_1381, n_940);
  not g1112 (n_1382, n_944);
  not g1113 (n_1383, n_952);
  not g1114 (n_1384, n_953);
  nand g1115 (n_664, n_1380, n_1381);
  nand g1116 (n_1385, n_899, n_898, n_900, n_1317);
  not g1117 (n_1386, n_1385);
  nand g1118 (n_715, n_1369, n_1370, n_1386);
  nand g1119 (n_1387, n_901, n_902, n_898, n_1317);
  not g1120 (n_1388, n_1387);
  nand g1121 (prim_out[17], n_1378, n_1388);
  nand g1122 (n_912, ctl_sel_prim_412_12_n_467, n_1338);
  not g1123 (n_1389, n_912);
  nor g1124 (n_1314, ctl_sel_prim_412_12_n_538, prim_out[1], n_1373,
       n_1389);
  not g1125 (n_1390, n_1314);
  nand g1126 (n_654, prim_out[23], n_1390);
  nand g1127 (prim_out[25], n_1108, n_1390);
  nand g1128 (n_710, n_1379, prim_out[5]);
  nand g1129 (n_726, prim_out[30], n_1390);
  nand g1130 (prim_out[21], n_1382, n_907, n_912);
  nand g1131 (n_736, prim_out[28], n_1317);
  nand g1132 (n_1391, n_901, n_904, n_898, n_1317);
  not g1133 (n_1392, n_1391);
  nand g1134 (n_753, prim_out[5], n_905, n_1392);
  nand g1135 (n_1393, n_890, n_903, n_900, n_1317);
  not g1136 (n_1394, n_1393);
  nand g1137 (n_1395, n_904, n_907, n_912, n_1390);
  not g1138 (n_1396, n_1395);
  nand g1139 (prim_out[29], n_1394, n_1396);
  nand g1140 (n_1397, n_890, n_907, n_898, n_1317);
  not g1141 (n_1398, n_1397);
  nand g1142 (n_1399, prim_out[5], n_911, n_912, n_1390);
  not g1143 (n_1400, n_1399);
  nand g1144 (n_778, n_1398, n_1400);
  nand g1145 (n_1401, n_891, n_905, n_898, n_1317);
  not g1146 (n_1402, n_1401);
  nand g1147 (n_1403, n_891, n_908, n_909, n_1317);
  not g1148 (n_1404, n_1403);
  nand g1149 (n_1405, n_1375, n_1376, n_1377, n_911);
  not g1150 (n_1406, n_1405);
  nand g1151 (n_1407, n_1371, n_1372, n_1374, n_1383);
  not g1152 (n_1408, n_1407);
  nand g1153 (n_1409, n_1384, n_911, n_918, n_919);
  not g1154 (n_1410, n_1409);
  nand g1155 (prim_out[26], n_912, n_1406);
  nand g1156 (prim_out[15], n_912, n_1408);
  not g1157 (n_1411, prim_out[15]);
  nand g1158 (prim_out[12], n_912, n_1410);
  nand g1159 (prim_out[27], prim_out[5], n_1402, n_1390);
  nand g1160 (prim_out[7], n_1390, n_1317);
  not g1161 (n_1412, prim_out[7]);
  nand g1162 (prim_out[11], prim_out[5], n_1404, n_1390);
  nand g1163 (prim_out[6], prim_out[5], n_1411);
  nand g1164 (prim_out[14], prim_out[5], n_1412);
endmodule

